### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [ticklemynausea/popen-noshell#6]
This project looks great, which license does it use?

**Comment by ticklemynausea** [comment]
Hi

it's free. I don't really have any preference for any formal license. 

Most code isn't ours, anyway. All we did was librarify the original source (http://cnds.eecs.jacobs-university.de/courses/os-2011/src/popen/popen.c) and make small modifications to spawn processes directly. Originally no license was specified either. I'm adding a README since most people may miss this credit since it's tucked away in the .h file.

Thanks

**Comment by ghost** [comment]
Thanks for reply!
